name: "AWS S3 cache for GitHub Actions"
description: "GitHub Action that allows you to cache build artifacts to S3"
branding:
  icon: "archive"
  color: "green"
inputs:
  action:
    description: "Action to perform. Options are: put, get, delete"
    required: true
  aws-access-key-id:
    description: "AWS access key id to access your bucket"
    required: false
  aws-secret-access-key:
    description: "AWS secret access key to access your bucket"
    required: false
  aws-session-token:
    description: "AWS temporary session token associated with having assumed a role"
    required: false
  aws-region:
    description: "AWS region where your bucket is located"
    required: true
  bucket:
    description: "AWS s3 bucket to store the artifacts"
    required: true
  key:
    description: "An explicit key for restoring and saving the cache"
    required: true
  default-key:
    description: "A default key for restoring similar cache in case the main key is not found"
    required: true
  artifacts:
    description: "A list of files, directories and glob patterns to cache and restore"
    required: false
  s3-class:
    description: "Specifies the desired Storage Class for the object."
    required: false
    default: STANDARD
  compression:
    description: "Compression method for the archive. Options: zstd, none (plain tar)"
    required: false
    default: zstd
  compression-level:
    description: "Compression level (zstd: 1-19). Leave empty for codec default. Ignored when compression is 'none'."
    required: false
  upload-concurrency:
    description: "Number of parallel parts for multipart S3 upload"
    required: false
    default: "10"
  download-concurrency:
    description: "Number of parallel parts for multipart S3 download"
    required: false
    default: "10"
  upload-part-size:
    description: "Part size for multipart S3 upload (e.g. 10MB, 50MiB). Leave empty for auto-calculation."
    required: false
  download-part-size:
    description: "Part size for multipart S3 download (e.g. 10MB, 50MiB). Default: 5MB."
    required: false
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        ACTION: ${{ inputs.action }}
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_SESSION_TOKEN: ${{ inputs.aws-session-token }}
        AWS_REGION: ${{ inputs.aws-region }}
        BUCKET: ${{ inputs.bucket }}
        S3_CLASS: ${{ inputs.s3-class }}
        KEY: ${{ inputs.key }}
        DEFAULT_KEY: ${{ inputs.default-key }}
        ARTIFACTS: ${{ inputs.artifacts }}
        OS: ${{ runner.os }}
        COMPRESSION: ${{ inputs.compression }}
        COMPRESSION_LEVEL: ${{ inputs.compression-level }}
        UPLOAD_CONCURRENCY: ${{ inputs.upload-concurrency }}
        DOWNLOAD_CONCURRENCY: ${{ inputs.download-concurrency }}
        UPLOAD_PART_SIZE: ${{ inputs.upload-part-size }}
        DOWNLOAD_PART_SIZE: ${{ inputs.download-part-size }}
